apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mysecondapp
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: main
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 3000
     - name: db
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb